import type { Metadata } from "next";

import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import { Anek_Telugu } from "next/font/google";
import { Footer } from "../features/layout/Footer";
import { Header } from "../features/layout/Header";
import { ThemeProvider } from "../features/theme/ThemeProvider";
import { cn } from "../lib/utils";
import "./globals.css";




const AnekTelugu = Anek_Telugu({
  subsets: ["latin"],
  variable: "--font-caption",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en" className="h-full">

      <body className={cn(GeistSans.variable,
        GeistMono.variable,
        AnekTelugu.variable,
        "font-sans h-full bg-background text-foreground"
      )}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex flex-col h-full">
            <Header />
            <div className="flex-1 max-w-lg m-auto py-10 w-full">
              {children}
            </div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
