import type { Metadata } from "next";

import { Toaster } from "@/components/ui/toaster";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import { Anek_Telugu } from "next/font/google";
import { ThemeProvider } from "../features/theme/ThemeProvider";
import { cn } from "../lib/utils";
import "./globals.css";
import { Providers } from "./providers";



export const AnekTelugu = Anek_Telugu({
  subsets: ["latin"],
  variable: "--font-caption",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en" >

      <body className={cn(GeistSans.variable,
        GeistMono.variable,
        AnekTelugu.variable,
        "font-sans min-h-screen bg-background text-foreground"
      )}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex flex-col h-full">
            <div className="flex-1  w-full">
              {/* max-w-lg m-auto  */}
              <Providers>
                {children}
              </Providers>
            </div>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
